language: clojure
before_script: test/support/setup_deps.sh
script:
  - make check
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk6
  - openjdk7
  #- openjdk8
#addons:
#  apt:
#    sources:
#      -
notifications:
  email:
      # the following won't work until the Travis
      # but here is sorted:
      # https://github.com/travis-ci/travis-ci/issues/2513
      - lcmap-dev-notifications@googlegroups.com
      - duncan.mcgreggor.ctr@usgs.gov
  slack:
    rooms:
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
      - lcmap:UTqlh9PfPVomfpli10WKyZoh#see

